services:
  wallet-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app/backend
    depends_on:
      - wallet-postgres
    networks:
      - wallet-network
    environment:
      DB_SERVER: wallet-postgres
      DB_NAME: walletdb
      DB_USER: postgres
      DB_PASSWORD: Password123!
    command: >
      bash -c "
      sleep 10s &&
      npm run dev
      "

  wallet-postgres:
    image: postgres:17
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123!
    ports:
      - "5432:5432"
    networks:
      - wallet-network
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s

networks:
  wallet-network:
    driver: bridge
