services:
  # Backend service
  wallet-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
        - .:/app
    working_dir: /app/backend
    depends_on:
      - wallet-sqlserver
    networks:
      - wallet-network
    environment:
      DB_SERVER: sqlserver
      DB_NAME: walletDB
      DB_USER: dbAdmin
      DB_PASSWORD: Password123!
    entrypoint: >
      /bin/sh -c "
      sleep 30 && 
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  # SQL Server service
  wallet-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wallet-sqlserver
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    networks:
        - wallet-network
    volumes:
        - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 30s && 
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Password123! -C -i /docker-entrypoint-initdb.d/init.sql && 
      tail -f /dev/null
      "

  # Frontend service

networks:
    wallet-network:
        driver: bridge
