services:
  wallet-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
        - .:/app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload