name: build and test on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      working-directory: ./backend
      run: npm install

    - name: Test
      working-directory: ./backend
      run: npm run test
